import Head from "next/head";
import Link from "next/link";
import Topnav from "../components/Topnav";

const Layout = ({ children }) => {
  return (
    <main class="flex flex-wrap md:flex-nowrap md:flex-col md:items-stretch md:h-screen">
      <Head>
        <title>Plantones</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/plantone-icon.ico" />
      </Head>
      <Topnav />
      <section class="flex flex-wrap md:flex-auto md:overflow-hidden">
        {children}
      </section>
    </main>
  );
};

export default Layout;
